# Generated by Django 4.1 on 2024-04-21 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('metric', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/product/')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('amount_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metric.amountunit', verbose_name='Единица измерения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metric.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductToAddedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('added_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products_added', to='product.product', verbose_name='Добавленный продукт')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_added_products', to='product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Продукты внутри продукта',
                'verbose_name_plural': 'Продукты внутри продукта',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Продукты внутри продукта',
                'verbose_name_plural': 'Продукты внутри продукта',
            },
        ),
    ]
