# Generated by Django 4.1 on 2024-04-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Количество добавленных'),
        ),
    ]
