# Generated by Django 4.1 on 2024-04-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('link', models.CharField(max_length=128, verbose_name='Ссылка')),
                ('wallpaper', models.ImageField(upload_to='media/poster/', verbose_name='Обои')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Постер',
                'verbose_name_plural': 'Постеры',
            },
        ),
    ]
