# Generated by Django 4.1 on 2024-04-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_rename_title_poster_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Показывается ли'),
        ),
    ]
