# Generated by Django 4.1 on 2024-04-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_poster_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='wallpaper',
            field=models.ImageField(upload_to='poster/', verbose_name='Обои'),
        ),
    ]
