# Generated by Django 4.1 on 2024-04-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metric', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amountunit',
            options={'verbose_name': 'Единица измерения', 'verbose_name_plural': 'Единицы измерения'},
        ),
    ]
